# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BdotDowloader
                                 A QGIS plugin
 pobiera BDOT i uzupełnia bazę danych
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-12-16
        copyright            : (C) 2022 by Kamil Drejer
        email                : kamil.drejer@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BdotDowloader class from file BdotDowloader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .bdot_downloader import BdotDowloader
    return BdotDowloader(iface)
